// ─────────────────────────────────────────────────────────────────────────────
// @crewshift/shared - AI Service Types
// Types exchanged between the Node API and the Python AI service.
// ─────────────────────────────────────────────────────────────────────────────

// ── Reasoning (LLM completion) ──────────────────────────────────────────────

/**
 * Request payload for the `/reason` AI endpoint.
 * Sends a templated prompt to an LLM and optionally enforces
 * a structured output schema.
 */
export interface ReasonRequest {
  /** Jinja2 / Mustache template for the user prompt. */
  prompt_template: string;
  /** Key-value pairs injected into the prompt template. */
  variables: Record<string, unknown>;
  /** Which model tier to route to (cost vs. capability trade-off). */
  model_tier: 'fast' | 'capable' | 'powerful';
  /** Optional system prompt prepended to the conversation. */
  system_prompt?: string;
  /** Optional JSON Schema the LLM must conform its output to. */
  output_schema?: Record<string, unknown>;
  /** UUID of the requesting organization (for billing / rate-limiting). */
  org_id: string;
  /** Idempotency / correlation key. */
  request_id: string;
}

/**
 * Response payload returned by the `/reason` AI endpoint.
 */
export interface ReasonResponse {
  /** Raw text content generated by the model. */
  content: string;
  /** Parsed structured output when an output_schema was provided. */
  structured_output?: unknown;
  /** Model identifier that actually served the request. */
  model_used: string;
  /** Total tokens (prompt + completion) consumed. */
  tokens_used: number;
  /** Estimated cost in cents. */
  cost_cents: number;
  /** End-to-end latency in milliseconds. */
  latency_ms: number;
  /** AI provider that served the request (e.g. "openai", "anthropic"). */
  provider: string;
}

// ── Classification (intent + entity extraction) ─────────────────────────────

/**
 * Request payload for the `/classify` AI endpoint.
 * Determines the user's intent and extracts named entities.
 */
export interface ClassifyRequest {
  /** The raw text to classify. */
  text: string;
  /** Candidate category labels the model should choose from. */
  categories: string[];
  /** UUID of the requesting organization. */
  org_id: string;
  /** Idempotency / correlation key. */
  request_id: string;
}

/**
 * Response payload returned by the `/classify` AI endpoint.
 */
export interface ClassifyResponse {
  /** The predicted intent / category. */
  intent: string;
  /** Named entities extracted from the text. */
  entities: Record<string, unknown>;
  /** Model's confidence in the classification (0-1). */
  confidence: number;
  /** Model identifier that served the request. */
  model_used: string;
}

// ── Structured extraction ───────────────────────────────────────────────────

/**
 * Request payload for the `/extract` AI endpoint.
 * Pulls structured data out of unstructured text according
 * to a caller-supplied schema.
 */
export interface ExtractRequest {
  /** The raw text to extract from. */
  text: string;
  /** JSON Schema describing the desired output shape. */
  schema: Record<string, unknown>;
  /** UUID of the requesting organization. */
  org_id: string;
  /** Idempotency / correlation key. */
  request_id: string;
}

/**
 * Response payload returned by the `/extract` AI endpoint.
 */
export interface ExtractResponse {
  /** The extracted key-value pairs conforming to the requested schema. */
  extracted: Record<string, unknown>;
  /** Model's confidence in the extraction (0-1). */
  confidence: number;
  /** Model identifier that served the request. */
  model_used: string;
}

// ── Transcription (speech-to-text) ──────────────────────────────────────────

/**
 * Request payload for the `/transcribe` AI endpoint.
 * Converts an audio file to text.
 */
export interface TranscribeRequest {
  /** Publicly-accessible URL of the audio file. */
  audio_url: string;
  /** BCP-47 language code hint (e.g. "en-US"). Defaults to auto-detect. */
  language?: string;
  /** UUID of the requesting organization. */
  org_id: string;
  /** Idempotency / correlation key. */
  request_id: string;
}

/**
 * Response payload returned by the `/transcribe` AI endpoint.
 */
export interface TranscribeResponse {
  /** Full transcribed text. */
  text: string;
  /** Detected or confirmed language code. */
  language: string;
  /** Duration of the audio in seconds. */
  duration_seconds: number;
  /** Model identifier that served the request. */
  model_used: string;
}

// ── Vision (image analysis) ─────────────────────────────────────────────────

/**
 * Request payload for the `/vision` AI endpoint.
 * Analyzes one or more images with a text prompt.
 */
export interface VisionRequest {
  /** Publicly-accessible URLs of the images to analyze. */
  image_urls: string[];
  /** Text prompt describing what to look for or extract. */
  prompt: string;
  /** UUID of the requesting organization. */
  org_id: string;
  /** Idempotency / correlation key. */
  request_id: string;
}

/**
 * Response payload returned by the `/vision` AI endpoint.
 */
export interface VisionResponse {
  /** Free-text analysis of the images. */
  analysis: string;
  /** Parsed structured output if the prompt requested it. */
  structured_output?: unknown;
  /** Model identifier that served the request. */
  model_used: string;
}

// ── Embeddings ──────────────────────────────────────────────────────────────

/**
 * Request payload for the `/embed` AI endpoint.
 * Generates vector embeddings for a batch of texts.
 */
export interface EmbedRequest {
  /** Array of text strings to embed. */
  texts: string[];
  /** Optional model override (defaults to the service's configured model). */
  model?: string;
  /** UUID of the requesting organization. */
  org_id: string;
}

/**
 * Response payload returned by the `/embed` AI endpoint.
 */
export interface EmbedResponse {
  /** Array of embedding vectors, one per input text. */
  embeddings: number[][];
  /** Model identifier that served the request. */
  model_used: string;
  /** Dimensionality of each embedding vector. */
  dimensions: number;
}

// ── Semantic search ─────────────────────────────────────────────────────────

/** A single result from a semantic search query. */
export interface SearchResult {
  /** The type of source document (e.g. "job", "invoice", "note"). */
  source_type: string;
  /** UUID of the source record. */
  source_id: string;
  /** The matched text content. */
  content: string;
  /** Cosine similarity score (0-1). */
  score: number;
  /** Additional metadata about the matched document. */
  metadata: Record<string, unknown>;
}

/**
 * Request payload for the `/search` AI endpoint.
 * Performs semantic (vector) search across an org's indexed data.
 */
export interface SearchRequest {
  /** Natural-language search query. */
  query: string;
  /** UUID of the requesting organization. */
  org_id: string;
  /** Optional filter to restrict which source types are searched. */
  source_types?: string[];
  /** Maximum number of results to return. */
  limit?: number;
}

/**
 * Response payload returned by the `/search` AI endpoint.
 */
export interface SearchResponse {
  /** Ranked list of matching documents. */
  results: SearchResult[];
}
