/* ------------------------------------------------------------------ */
/*  Integration Registry — 103 Trade Business Software Integrations   */
/* ------------------------------------------------------------------ */

import type {
  IntegrationEntry,
  IntegrationCategory,
  IntegrationTier,
} from './types';

/* ================================================================== */
/*  INTEGRATIONS — Master List                                        */
/* ================================================================== */

export const INTEGRATIONS: readonly IntegrationEntry[] = [
  /* ---------------------------------------------------------------- */
  /*  TIER 1 — Free Instant Access (33)                               */
  /* ---------------------------------------------------------------- */

  // -- Payments (7) ------------------------------------------------
  {
    slug: 'stripe',
    name: 'Stripe',
    description: 'Online payment processing',
    category: 'payments',
    icon: 'credit-card',
    website: 'stripe.com',
    authType: 'bearer_token',
    tier: 1,
    docsUrl: 'https://docs.stripe.com/api',
    apiBaseUrl: 'https://api.stripe.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '25 req/sec',
  },
  {
    slug: 'paypal',
    name: 'PayPal',
    description: 'Payment processing and invoicing',
    category: 'payments',
    icon: 'credit-card',
    website: 'paypal.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://developer.paypal.com/api/rest/',
    apiBaseUrl: 'https://api.paypal.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Varies by endpoint',
  },
  {
    slug: 'braintree',
    name: 'Braintree',
    description: 'Payment gateway',
    category: 'payments',
    icon: 'credit-card',
    website: 'braintreepayments.com',
    authType: 'api_key',
    tier: 1,
    docsUrl: 'https://developer.paypal.com/braintree/docs/',
    apiBaseUrl: 'https://payments.braintree-api.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Varies by endpoint',
  },
  {
    slug: 'helcim',
    name: 'Helcim',
    description: 'Payment processing for SMBs',
    category: 'payments',
    icon: 'credit-card',
    website: 'helcim.com',
    authType: 'bearer_token',
    tier: 1,
    docsUrl: 'https://devdocs.helcim.com',
    apiBaseUrl: 'https://api.helcim.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'HMAC webhooks',
  },
  {
    slug: 'stax',
    name: 'Stax',
    description: 'Flat-rate payment processing',
    category: 'payments',
    icon: 'credit-card',
    website: 'staxpayments.com',
    authType: 'bearer_token',
    tier: 1,
    docsUrl: 'https://docs.staxpayments.com',
    apiBaseUrl: 'https://api.staxpayments.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
  },
  {
    slug: 'authorize-net',
    name: 'Authorize.net',
    description: 'Payment gateway',
    category: 'payments',
    icon: 'credit-card',
    website: 'authorize.net',
    authType: 'basic_auth',
    tier: 1,
    docsUrl: 'https://developer.authorize.net',
    apiBaseUrl: 'https://api.authorize.net',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Login ID + Transaction Key',
  },
  {
    slug: 'gocardless',
    name: 'GoCardless',
    description: 'Direct debit payments',
    category: 'payments',
    icon: 'credit-card',
    website: 'gocardless.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://developer.gocardless.com',
    apiBaseUrl: 'https://api.gocardless.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '1000 req/min',
  },

  // -- Communication (7) -------------------------------------------
  {
    slug: 'twilio',
    name: 'Twilio',
    description: 'SMS, voice, and messaging',
    category: 'communication',
    icon: 'phone',
    website: 'twilio.com',
    authType: 'basic_auth',
    tier: 1,
    docsUrl: 'https://twilio.com/docs',
    apiBaseUrl: 'https://api.twilio.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '100 req/sec',
    notes: 'Account SID + Auth Token',
  },
  {
    slug: 'signalwire',
    name: 'SignalWire',
    description: 'Telecom APIs',
    category: 'communication',
    icon: 'phone',
    website: 'signalwire.com',
    authType: 'basic_auth',
    tier: 1,
    docsUrl: 'https://developer.signalwire.com',
    apiBaseUrl: 'https://<space>.signalwire.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Project ID + Token; HMAC webhooks',
  },
  {
    slug: 'vonage',
    name: 'Vonage (Nexmo)',
    description: 'Communication APIs',
    category: 'communication',
    icon: 'phone',
    website: 'vonage.com',
    authType: 'jwt',
    tier: 1,
    docsUrl: 'https://developer.vonage.com',
    apiBaseUrl: 'https://api.nexmo.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'JWT or Basic Auth',
  },
  {
    slug: 'sendgrid',
    name: 'SendGrid',
    description: 'Email delivery',
    category: 'communication',
    icon: 'mail',
    website: 'sendgrid.com',
    authType: 'bearer_token',
    tier: 1,
    docsUrl: 'https://docs.sendgrid.com',
    apiBaseUrl: 'https://api.sendgrid.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'No rate limit on send',
  },
  {
    slug: 'postmark',
    name: 'Postmark',
    description: 'Transactional email',
    category: 'communication',
    icon: 'mail',
    website: 'postmarkapp.com',
    authType: 'bearer_token',
    tier: 1,
    docsUrl: 'https://postmarkapp.com/developer',
    apiBaseUrl: 'https://api.postmarkapp.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Server Token header',
  },
  {
    slug: 'mailchimp',
    name: 'Mailchimp',
    description: 'Email marketing',
    category: 'communication',
    icon: 'mail',
    website: 'mailchimp.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://mailchimp.com/developer/',
    apiBaseUrl: 'https://<dc>.api.mailchimp.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '10 concurrent connections',
  },
  {
    slug: 'slack',
    name: 'Slack',
    description: 'Team messaging',
    category: 'communication',
    icon: 'message-square',
    website: 'slack.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://api.slack.com',
    apiBaseUrl: 'https://slack.com/api',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '1 req/sec per method',
  },

  // -- Scheduling (3) ----------------------------------------------
  {
    slug: 'google-calendar',
    name: 'Google Calendar',
    description: 'Calendar scheduling',
    category: 'scheduling',
    icon: 'calendar',
    website: 'calendar.google.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://developers.google.com/calendar/api',
    apiBaseUrl: 'https://www.googleapis.com/calendar/v3',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '1M queries/day',
    notes: 'Push notifications',
  },
  {
    slug: 'calendly',
    name: 'Calendly',
    description: 'Appointment scheduling',
    category: 'scheduling',
    icon: 'calendar',
    website: 'calendly.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://developer.calendly.com',
    apiBaseUrl: 'https://api.calendly.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'PAT or OAuth 2.1; Webhooks on paid plans',
  },
  {
    slug: 'acuity-scheduling',
    name: 'Acuity Scheduling',
    description: 'Online appointment scheduling',
    category: 'scheduling',
    icon: 'calendar',
    website: 'acuityscheduling.com',
    authType: 'basic_auth',
    tier: 1,
    docsUrl: 'https://developers.acuityscheduling.com',
    apiBaseUrl: 'https://acuityscheduling.com/api/v1',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
  },

  // -- Fleet (4) ---------------------------------------------------
  {
    slug: 'route4me',
    name: 'Route4Me',
    description: 'Route optimization',
    category: 'fleet',
    icon: 'truck',
    website: 'route4me.com',
    authType: 'api_key',
    tier: 1,
    docsUrl: 'https://route4me.io/docs/',
    apiBaseUrl: 'https://api.route4me.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: 'Standard',
    notes: 'SDKs in 12+ languages',
  },
  {
    slug: 'optimoroute',
    name: 'OptimoRoute',
    description: 'Route planning and optimization',
    category: 'fleet',
    icon: 'truck',
    website: 'optimoroute.com',
    authType: 'api_key',
    tier: 1,
    docsUrl: 'https://optimoroute.com/api/',
    apiBaseUrl: 'https://api.optimoroute.com',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: 'Max 5 concurrent requests',
  },
  {
    slug: 'samsara',
    name: 'Samsara',
    description: 'Fleet management and telematics',
    category: 'fleet',
    icon: 'truck',
    website: 'samsara.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://developers.samsara.com',
    apiBaseUrl: 'https://api.samsara.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'general', 'construction'],
    rateLimits: '150 req/sec',
  },
  {
    slug: 'gps-trackit',
    name: 'GPS Trackit',
    description: 'Vehicle GPS tracking',
    category: 'fleet',
    icon: 'truck',
    website: 'gpstrackit.com',
    authType: 'api_key',
    tier: 1,
    docsUrl: 'https://api-docs.gpstrackit.com',
    apiBaseUrl: 'https://api.gpstrackit.com',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: '50 queries/min',
  },

  // -- Accounting (6) ----------------------------------------------
  {
    slug: 'quickbooks-online',
    name: 'QuickBooks Online',
    description: 'Accounting and bookkeeping',
    category: 'accounting',
    icon: 'calculator',
    website: 'quickbooks.intuit.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://developer.intuit.com',
    apiBaseUrl: 'https://quickbooks.api.intuit.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '500 req/min',
    notes: '#1 priority; ~80% market share; HMAC webhooks',
  },
  {
    slug: 'xero',
    name: 'Xero',
    description: 'Cloud accounting',
    category: 'accounting',
    icon: 'calculator',
    website: 'xero.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://developer.xero.com',
    apiBaseUrl: 'https://api.xero.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '60 req/min + 5K/day',
    notes: 'HMAC webhooks',
  },
  {
    slug: 'freshbooks',
    name: 'FreshBooks',
    description: 'Invoicing and accounting',
    category: 'accounting',
    icon: 'calculator',
    website: 'freshbooks.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://freshbooks.com/api/start',
    apiBaseUrl: 'https://api.freshbooks.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: '15min token expiry',
  },
  {
    slug: 'wave',
    name: 'Wave',
    description: 'Free accounting software',
    category: 'accounting',
    icon: 'calculator',
    website: 'waveapps.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://developer.waveapps.com',
    apiBaseUrl: 'https://gql.waveapps.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'GraphQL API',
  },
  {
    slug: 'myob',
    name: 'MYOB',
    description: 'Accounting software (ANZ)',
    category: 'accounting',
    icon: 'calculator',
    website: 'myob.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://developer.myob.com',
    apiBaseUrl: 'https://api.myob.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '8 req/sec + 1M/day',
  },
  {
    slug: 'zoho-books',
    name: 'Zoho Books',
    description: 'Online accounting',
    category: 'accounting',
    icon: 'calculator',
    website: 'zoho.com/books',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://zoho.com/books/api/v3/',
    apiBaseUrl: 'https://books.zoho.com/api/v3',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '100 req/min',
  },

  // -- Government/Compliance (2) -----------------------------------
  {
    slug: 'epa-envirofacts',
    name: 'EPA Envirofacts',
    description: 'Environmental compliance data',
    category: 'government',
    icon: 'shield',
    website: 'epa.gov/enviro',
    authType: 'api_key',
    tier: 1,
    docsUrl: 'https://epa.gov/enviro/envirofacts-data-service-api',
    apiBaseUrl: 'https://enviro.epa.gov/enviro/efservice',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'environmental'],
    rateLimits: 'Unlimited',
    notes: 'No auth required; Free',
  },
  {
    slug: 'osha-ita',
    name: 'OSHA ITA',
    description: 'Injury reporting and compliance',
    category: 'government',
    icon: 'shield',
    website: 'osha.gov',
    authType: 'api_key',
    tier: 1,
    docsUrl: 'https://osha.gov/injuryreporting',
    apiBaseUrl: 'https://www.osha.gov/injuryreporting/api',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Free',
  },

  // -- Specialty (4) -----------------------------------------------
  {
    slug: 'safetyculture',
    name: 'SafetyCulture (iAuditor)',
    description: 'Inspections and audits',
    category: 'specialty',
    icon: 'clipboard-check',
    website: 'safetyculture.com',
    authType: 'bearer_token',
    tier: 1,
    docsUrl: 'https://developer.safetyculture.com',
    apiBaseUrl: 'https://api.safetyculture.io',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: '30-day token expiry',
  },
  {
    slug: 'surveymonkey',
    name: 'SurveyMonkey',
    description: 'Surveys and feedback',
    category: 'specialty',
    icon: 'clipboard-list',
    website: 'surveymonkey.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://api.surveymonkey.com',
    apiBaseUrl: 'https://api.surveymonkey.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '120 req/min',
  },
  {
    slug: 'typeform',
    name: 'Typeform',
    description: 'Forms and surveys',
    category: 'specialty',
    icon: 'clipboard-list',
    website: 'typeform.com',
    authType: 'oauth2',
    tier: 1,
    docsUrl: 'https://typeform.com/developers/',
    apiBaseUrl: 'https://api.typeform.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'PAT or OAuth; HMAC webhooks',
  },
  {
    slug: 'trello',
    name: 'Trello',
    description: 'Project boards',
    category: 'specialty',
    icon: 'layout-grid',
    website: 'trello.com',
    authType: 'api_key',
    tier: 1,
    docsUrl: 'https://developer.atlassian.com/cloud/trello/',
    apiBaseUrl: 'https://api.trello.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '300 req/10sec',
  },

  /* ---------------------------------------------------------------- */
  /*  TIER 2 — Free Dev Account + OAuth Setup (24)                    */
  /* ---------------------------------------------------------------- */

  // -- FSM & CRM (8) -----------------------------------------------
  {
    slug: 'jobber',
    name: 'Jobber',
    description: 'Field service management',
    category: 'fsm',
    icon: 'wrench',
    website: 'getjobber.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developer.getjobber.com',
    apiBaseUrl: 'https://api.getjobber.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'landscaping', 'cleaning'],
    rateLimits: '2500 req/5min',
    notes: 'GraphQL; 90-day sandbox',
  },
  {
    slug: 'servicem8',
    name: 'ServiceM8',
    description: 'Job management for trades',
    category: 'fsm',
    icon: 'wrench',
    website: 'servicem8.com',
    authType: 'api_key',
    tier: 2,
    docsUrl: 'https://developer.servicem8.com',
    apiBaseUrl: 'https://api.servicem8.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: '20K req/day',
  },
  {
    slug: 'simpro',
    name: 'Simpro',
    description: 'Trade business management',
    category: 'fsm',
    icon: 'wrench',
    website: 'simprogroup.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developer.simprogroup.com',
    apiBaseUrl: 'https://api.simprogroup.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'construction'],
    rateLimits: '10 req/sec (strict)',
  },
  {
    slug: 'zuper',
    name: 'Zuper',
    description: 'Field service platform',
    category: 'fsm',
    icon: 'wrench',
    website: 'zuper.co',
    authType: 'api_key',
    tier: 2,
    docsUrl: 'https://developers.zuper.co',
    apiBaseUrl: 'https://api.zuper.co',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: 'Standard',
    notes: 'Self-service API keys; SDK available',
  },
  {
    slug: 'fergus',
    name: 'Fergus',
    description: 'Trade job management',
    category: 'fsm',
    icon: 'wrench',
    website: 'fergus.com',
    authType: 'api_key',
    tier: 2,
    docsUrl: 'https://api.fergus.com/docs',
    apiBaseUrl: 'https://api.fergus.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: 'Standard',
    notes: 'OpenAPI 3.0 spec',
  },
  {
    slug: 'procore',
    name: 'Procore',
    description: 'Construction management',
    category: 'fsm',
    icon: 'hard-hat',
    website: 'procore.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developers.procore.com',
    apiBaseUrl: 'https://api.procore.com',
    webhookSupport: true,
    trades: ['construction', 'general'],
    rateLimits: '3600 req/hr',
    notes: 'Free sandbox',
  },
  {
    slug: 'acculynx',
    name: 'AccuLynx',
    description: 'Roofing management',
    category: 'fsm',
    icon: 'wrench',
    website: 'acculynx.com',
    authType: 'bearer_token',
    tier: 2,
    docsUrl: 'https://apidocs.acculynx.com',
    apiBaseUrl: 'https://api.acculynx.com',
    webhookSupport: true,
    trades: ['roofing'],
    rateLimits: '30 req/sec',
  },
  {
    slug: 'jobnimbus',
    name: 'JobNimbus',
    description: 'CRM for contractors',
    category: 'crm',
    icon: 'users',
    website: 'jobnimbus.com',
    authType: 'bearer_token',
    tier: 2,
    docsUrl: 'https://app.jobnimbus.com/api',
    apiBaseUrl: 'https://app.jobnimbus.com/api1',
    webhookSupport: false,
    trades: ['roofing', 'general', 'construction'],
    rateLimits: 'Standard',
    notes: 'Self-service; Postman docs',
  },

  // -- Payments (2) ------------------------------------------------
  {
    slug: 'square',
    name: 'Square',
    description: 'Payment processing',
    category: 'payments',
    icon: 'credit-card',
    website: 'squareup.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developer.squareup.com',
    apiBaseUrl: 'https://connect.squareup.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
  },
  {
    slug: 'clover',
    name: 'Clover',
    description: 'POS and payments',
    category: 'payments',
    icon: 'credit-card',
    website: 'clover.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://docs.clover.com',
    apiBaseUrl: 'https://api.clover.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '16 req/sec',
  },

  // -- Communication (3) -------------------------------------------
  {
    slug: 'ringcentral',
    name: 'RingCentral',
    description: 'Business phone system',
    category: 'communication',
    icon: 'phone',
    website: 'ringcentral.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developers.ringcentral.com',
    apiBaseUrl: 'https://platform.ringcentral.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '40 req/min',
  },
  {
    slug: 'microsoft-teams',
    name: 'Microsoft Teams',
    description: 'Team collaboration',
    category: 'communication',
    icon: 'message-square',
    website: 'microsoft.com/teams',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://learn.microsoft.com/graph',
    apiBaseUrl: 'https://graph.microsoft.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '50 RPS/tenant',
    notes: 'Azure AD OAuth; Graph API',
  },
  {
    slug: 'constant-contact',
    name: 'Constant Contact',
    description: 'Email marketing',
    category: 'communication',
    icon: 'mail',
    website: 'constantcontact.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developer.constantcontact.com',
    apiBaseUrl: 'https://api.cc.email',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: '10K req/day',
  },

  // -- Estimating (2) ----------------------------------------------
  {
    slug: 'pandadoc',
    name: 'PandaDoc',
    description: 'Proposals and contracts',
    category: 'estimating',
    icon: 'file-text',
    website: 'pandadoc.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developers.pandadoc.com',
    apiBaseUrl: 'https://api.pandadoc.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '50 create/min',
  },
  {
    slug: 'docusign',
    name: 'DocuSign',
    description: 'Electronic signatures',
    category: 'estimating',
    icon: 'pen-tool',
    website: 'docusign.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developers.docusign.com',
    apiBaseUrl: 'https://<account>.docusign.net',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '3K req/hr',
    notes: 'OAuth 2.0 required; Webhooks via Connect',
  },

  // -- Specialty & Measurement (5) ---------------------------------
  {
    slug: 'companycam',
    name: 'CompanyCam',
    description: 'Job site photo documentation',
    category: 'specialty',
    icon: 'camera',
    website: 'companycam.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://docs.companycam.com',
    apiBaseUrl: 'https://api.companycam.com',
    webhookSupport: true,
    trades: ['roofing', 'construction', 'general'],
    rateLimits: 'Standard',
  },
  {
    slug: 'hover',
    name: 'Hover',
    description: '3D property measurement',
    category: 'measurement',
    icon: 'ruler',
    website: 'hover.to',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developers.hover.to',
    apiBaseUrl: 'https://api.hover.to',
    webhookSupport: true,
    trades: ['roofing', 'siding', 'construction'],
    rateLimits: '120 req/min',
    notes: 'Sandbox available',
  },
  {
    slug: 'eagleview',
    name: 'EagleView',
    description: 'Aerial property measurement',
    category: 'measurement',
    icon: 'ruler',
    website: 'eagleview.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developer.eagleview.com',
    apiBaseUrl: 'https://api.eagleview.com',
    webhookSupport: false,
    trades: ['roofing', 'solar', 'insurance'],
    rateLimits: 'Standard',
    notes: 'Free trial',
  },
  {
    slug: 'birdeye',
    name: 'Birdeye',
    description: 'Reputation management',
    category: 'reputation',
    icon: 'star',
    website: 'birdeye.com',
    authType: 'api_key',
    tier: 2,
    docsUrl: 'https://docs.birdeye.so',
    apiBaseUrl: 'https://api.birdeye.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'OpenAPI spec; API Keys + OAuth',
  },
  {
    slug: 'stack-ct',
    name: 'STACK',
    description: 'Construction takeoff',
    category: 'estimating',
    icon: 'file-text',
    website: 'stackct.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://stackct.com/developers-docs/',
    apiBaseUrl: 'https://api.stackct.com',
    webhookSupport: false,
    trades: ['construction', 'general'],
    rateLimits: 'Standard',
    notes: 'Tokens ~8hrs expiry',
  },

  // -- Misc (4) ----------------------------------------------------
  {
    slug: 'notion',
    name: 'Notion',
    description: 'Knowledge management',
    category: 'project_management',
    icon: 'book-open',
    website: 'notion.so',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developers.notion.com',
    apiBaseUrl: 'https://api.notion.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '3 req/sec',
    notes: 'HMAC webhooks',
  },
  {
    slug: 'monday',
    name: 'Monday.com',
    description: 'Work management',
    category: 'project_management',
    icon: 'kanban',
    website: 'monday.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developer.monday.com',
    apiBaseUrl: 'https://api.monday.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '5K complexity/min',
    notes: 'GraphQL; PAT or OAuth',
  },
  {
    slug: 'asana',
    name: 'Asana',
    description: 'Project management',
    category: 'project_management',
    icon: 'kanban',
    website: 'asana.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developers.asana.com',
    apiBaseUrl: 'https://app.asana.com/api/1.0',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '1500 req/min',
  },
  {
    slug: 'opengov',
    name: 'OpenGov',
    description: 'Government financial management',
    category: 'government',
    icon: 'landmark',
    website: 'opengov.com',
    authType: 'oauth2',
    tier: 2,
    docsUrl: 'https://developer.opengov.com',
    apiBaseUrl: 'https://api.opengov.com',
    webhookSupport: true,
    trades: ['government', 'construction'],
    rateLimits: 'Standard',
  },

  /* ---------------------------------------------------------------- */
  /*  TIER 3 — Developer Application Required (9)                     */
  /* ---------------------------------------------------------------- */
  {
    slug: 'podium',
    name: 'Podium',
    description: 'Customer interaction platform',
    category: 'reputation',
    icon: 'star',
    website: 'podium.com',
    authType: 'oauth2',
    tier: 3,
    docsUrl: 'https://developer.podium.com',
    apiBaseUrl: 'https://api.podium.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'OAuth 2.0/JWT; Few-day review',
  },
  {
    slug: 'nicejob',
    name: 'NiceJob',
    description: 'Reputation marketing',
    category: 'reputation',
    icon: 'star',
    website: 'nicejob.com',
    authType: 'oauth2',
    tier: 3,
    docsUrl: 'https://get.nicejob.com/partners/developers',
    apiBaseUrl: 'https://api.nicejob.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'API in ALPHA',
  },
  {
    slug: 'hatch',
    name: 'Hatch',
    description: 'Customer engagement',
    category: 'communication',
    icon: 'message-circle',
    website: 'usehatchapp.com',
    authType: 'api_key',
    tier: 3,
    docsUrl: 'https://usehatchapp.com',
    apiBaseUrl: 'https://api.usehatchapp.com',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'electrical', 'roofing'],
    rateLimits: 'Standard',
    notes: 'POST-based API key',
  },
  {
    slug: 'fieldedge',
    name: 'FieldEdge',
    description: 'Field service management',
    category: 'fsm',
    icon: 'wrench',
    website: 'fieldedge.com',
    authType: 'bearer_token',
    tier: 3,
    docsUrl: 'https://docs.api.fieldedge.com',
    apiBaseUrl: 'https://api.fieldedge.com',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'electrical'],
    rateLimits: 'Standard',
    notes: 'REST on Azure APIM',
  },
  {
    slug: 'verizon-connect',
    name: 'Verizon Connect',
    description: 'Fleet tracking',
    category: 'fleet',
    icon: 'truck',
    website: 'verizonconnect.com',
    authType: 'basic_auth',
    tier: 3,
    docsUrl: 'https://developer.verizonconnect.com',
    apiBaseUrl: 'https://api.verizonconnect.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: 'Standard',
  },
  {
    slug: 'leap',
    name: 'Leap',
    description: 'Home improvement sales',
    category: 'crm',
    icon: 'users',
    website: 'leaptodigital.com',
    authType: 'bearer_token',
    tier: 3,
    docsUrl: 'https://leaptodigital.com',
    apiBaseUrl: 'https://api.leaptodigital.com',
    webhookSupport: true,
    trades: ['roofing', 'windows', 'siding', 'general'],
    rateLimits: 'Standard',
    notes: 'Contact support to enable',
  },
  {
    slug: 'ferguson',
    name: 'Ferguson',
    description: 'Plumbing and HVAC supply',
    category: 'inventory',
    icon: 'package',
    website: 'ferguson.com',
    authType: 'api_key',
    tier: 3,
    docsUrl: 'https://developer.ferguson.com',
    apiBaseUrl: 'https://api.ferguson.com',
    webhookSupport: false,
    trades: ['hvac', 'plumbing'],
    rateLimits: 'Standard',
    notes: 'Apigee gateway; case-by-case',
  },
  {
    slug: 'bluebeam',
    name: 'Bluebeam Revu',
    description: 'PDF markup for construction',
    category: 'estimating',
    icon: 'file-text',
    website: 'bluebeam.com',
    authType: 'oauth2',
    tier: 3,
    docsUrl: 'https://support.bluebeam.com',
    apiBaseUrl: 'https://api.bluebeam.com',
    webhookSupport: true,
    trades: ['construction', 'general'],
    rateLimits: 'Standard',
    notes: 'Email integrations@bluebeam.com',
  },
  {
    slug: 'accela',
    name: 'Accela',
    description: 'Civic platform and permitting',
    category: 'government',
    icon: 'landmark',
    website: 'accela.com',
    authType: 'oauth2',
    tier: 3,
    docsUrl: 'https://developer.accela.com',
    apiBaseUrl: 'https://apis.accela.com',
    webhookSupport: false,
    trades: ['construction', 'general'],
    rateLimits: 'Standard',
    notes: 'OAuth 2.0 via CivicID',
  },

  /* ---------------------------------------------------------------- */
  /*  TIER 4 — Paid Plan Required (12)                                */
  /* ---------------------------------------------------------------- */
  {
    slug: 'housecall-pro',
    name: 'Housecall Pro',
    description: 'Home service management',
    category: 'fsm',
    icon: 'wrench',
    website: 'housecallpro.com',
    authType: 'oauth2',
    tier: 4,
    docsUrl: 'https://docs.housecallpro.com',
    apiBaseUrl: 'https://api.housecallpro.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'cleaning'],
    rateLimits: 'Standard',
    notes: 'MAX plan ~$249/mo required',
  },
  {
    slug: 'service-fusion',
    name: 'Service Fusion',
    description: 'Field service software',
    category: 'fsm',
    icon: 'wrench',
    website: 'servicefusion.com',
    authType: 'api_key',
    tier: 4,
    docsUrl: 'https://docs.servicefusion.com',
    apiBaseUrl: 'https://api.servicefusion.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical'],
    rateLimits: 'Standard',
    notes: 'PRO plan required',
  },
  {
    slug: 'workiz',
    name: 'Workiz',
    description: 'Service dispatch',
    category: 'fsm',
    icon: 'wrench',
    website: 'workiz.com',
    authType: 'bearer_token',
    tier: 4,
    docsUrl: 'https://developer.workiz.com',
    apiBaseUrl: 'https://api.workiz.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'locksmith'],
    rateLimits: 'Standard',
    notes: 'Developer API add-on',
  },
  {
    slug: 'kickserv',
    name: 'Kickserv',
    description: 'Service business management',
    category: 'fsm',
    icon: 'wrench',
    website: 'kickserv.com',
    authType: 'basic_auth',
    tier: 4,
    docsUrl: 'https://help.kickserv.com',
    apiBaseUrl: 'https://api.kickserv.com',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: 'Standard',
    notes: 'Premium plan required; Basic Auth + token',
  },
  {
    slug: 'fieldpulse',
    name: 'FieldPulse',
    description: 'Field service management',
    category: 'fsm',
    icon: 'wrench',
    website: 'fieldpulse.com',
    authType: 'bearer_token',
    tier: 4,
    docsUrl: 'https://help.fieldpulse.com',
    apiBaseUrl: 'https://api.fieldpulse.com',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: '1K req/hr',
    notes: 'Professional plan required',
  },
  {
    slug: 'inflow',
    name: 'inFlow Inventory',
    description: 'Inventory management',
    category: 'inventory',
    icon: 'package',
    website: 'inflowinventory.com',
    authType: 'api_key',
    tier: 4,
    docsUrl: 'https://cloudapi.inflowinventory.com',
    apiBaseUrl: 'https://cloudapi.inflowinventory.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: '60 req/min',
    notes: 'API paid add-on',
  },
  {
    slug: 'sortly',
    name: 'Sortly',
    description: 'Visual inventory management',
    category: 'inventory',
    icon: 'package',
    website: 'sortly.com',
    authType: 'oauth2',
    tier: 4,
    docsUrl: 'https://developer.sortly.com',
    apiBaseUrl: 'https://api.sortly.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: '1K req/15min',
    notes: 'Ultra/Enterprise plan',
  },
  {
    slug: 'proposify',
    name: 'Proposify',
    description: 'Proposal software',
    category: 'proposals',
    icon: 'file-text',
    website: 'proposify.com',
    authType: 'oauth2',
    tier: 4,
    docsUrl: 'https://api.proposify.com',
    apiBaseUrl: 'https://api.proposify.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Business plan + CS enablement',
  },
  {
    slug: 'fleetio',
    name: 'Fleetio',
    description: 'Fleet management',
    category: 'fleet',
    icon: 'truck',
    website: 'fleetio.com',
    authType: 'api_key',
    tier: 4,
    docsUrl: 'https://developer.fleetio.com',
    apiBaseUrl: 'https://secure.fleetio.com/api',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: '$4/vehicle/mo; HMAC webhooks',
  },
  {
    slug: 'sage-intacct',
    name: 'Sage Intacct',
    description: 'Enterprise accounting',
    category: 'accounting',
    icon: 'calculator',
    website: 'sage.com/intacct',
    authType: 'oauth2',
    tier: 4,
    docsUrl: 'https://developer.intacct.com',
    apiBaseUrl: 'https://api.intacct.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Subscription + dev license; REST or XML',
  },
  {
    slug: 'salesforce-field-service',
    name: 'Salesforce Field Service',
    description: 'Enterprise FSM',
    category: 'fsm',
    icon: 'cloud',
    website: 'salesforce.com',
    authType: 'oauth2',
    tier: 4,
    docsUrl: 'https://developer.salesforce.com',
    apiBaseUrl: 'https://<instance>.salesforce.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '~115K req/day',
    notes: '$150-300+/user/mo',
  },
  {
    slug: 'dynamics-365-fs',
    name: 'MS Dynamics 365 Field Service',
    description: 'Enterprise FSM',
    category: 'fsm',
    icon: 'cloud',
    website: 'microsoft.com/dynamics365',
    authType: 'oauth2',
    tier: 4,
    docsUrl: 'https://learn.microsoft.com/dynamics365',
    apiBaseUrl: 'https://<org>.api.crm.dynamics.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: '~40K req/24hr/user',
    notes: 'License required; Entra ID OAuth',
  },

  /* ---------------------------------------------------------------- */
  /*  TIER 5 — Partner/Enterprise Programs (11)                       */
  /* ---------------------------------------------------------------- */
  {
    slug: 'servicetitan',
    name: 'ServiceTitan',
    description: 'Trade business platform',
    category: 'fsm',
    icon: 'wrench',
    website: 'servicetitan.com',
    authType: 'oauth2',
    tier: 5,
    docsUrl: 'https://developer.servicetitan.io',
    apiBaseUrl: 'https://api.servicetitan.io',
    webhookSupport: true,
    trades: ['hvac', 'plumbing', 'electrical'],
    rateLimits: '60 req/sec',
    notes: 'Partner program PAUSED',
  },
  {
    slug: 'wepay',
    name: 'WePay (Chase)',
    description: 'Integrated payments',
    category: 'payments',
    icon: 'credit-card',
    website: 'wepay.com',
    authType: 'oauth2',
    tier: 5,
    docsUrl: 'https://dev.wepay.com',
    apiBaseUrl: 'https://api.wepay.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Platform partnership required',
  },
  {
    slug: 'melio',
    name: 'Melio',
    description: 'B2B payments',
    category: 'payments',
    icon: 'credit-card',
    website: 'meliopayments.com',
    authType: 'oauth2',
    tier: 5,
    docsUrl: 'https://meliopayments.com/partners/',
    apiBaseUrl: 'https://api.melio.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Partner program',
  },
  {
    slug: 'fundbox',
    name: 'Fundbox',
    description: 'Business financing',
    category: 'payments',
    icon: 'credit-card',
    website: 'fundbox.com',
    authType: 'oauth2',
    tier: 5,
    docsUrl: 'https://fundbox.com/partners/',
    apiBaseUrl: 'https://api.fundbox.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Partner program',
  },
  {
    slug: 'bench',
    name: 'Bench',
    description: 'Bookkeeping service',
    category: 'accounting',
    icon: 'calculator',
    website: 'bench.co',
    authType: 'api_key',
    tier: 5,
    docsUrl: 'https://bench.co/embedded-bookkeeping',
    apiBaseUrl: 'https://api.bench.co',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Embedded partner',
  },
  {
    slug: 'worldpay',
    name: 'Worldpay (FIS)',
    description: 'Payment processing',
    category: 'payments',
    icon: 'credit-card',
    website: 'worldpay.com',
    authType: 'basic_auth',
    tier: 5,
    docsUrl: 'https://developer.worldpay.com',
    apiBaseUrl: 'https://api.worldpay.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Implementation Manager required',
  },
  {
    slug: 'dispatch',
    name: 'Dispatch',
    description: 'Home services marketplace',
    category: 'fsm',
    icon: 'wrench',
    website: 'dispatch.me',
    authType: 'oauth2',
    tier: 5,
    docsUrl: 'https://dispatch.me',
    apiBaseUrl: 'https://api.dispatch.me',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'electrical'],
    rateLimits: 'Standard',
    notes: 'Enterprise only; Contact sales',
  },
  {
    slug: 'next-insurance',
    name: 'Next Insurance',
    description: 'Small business insurance',
    category: 'insurance',
    icon: 'shield-check',
    website: 'nextinsurance.com',
    authType: 'api_key',
    tier: 5,
    docsUrl: 'https://nextinsurance.com/become-a-partner/',
    apiBaseUrl: 'https://api.nextinsurance.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'NEXT Connect partner program',
  },
  {
    slug: 'thimble',
    name: 'Thimble',
    description: 'On-demand business insurance',
    category: 'insurance',
    icon: 'shield-check',
    website: 'thimble.com',
    authType: 'api_key',
    tier: 5,
    docsUrl: 'https://thimble.com/partner/api',
    apiBaseUrl: 'https://api.thimble.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Free partner API',
  },
  {
    slug: 'simply-business',
    name: 'Simply Business',
    description: 'Insurance marketplace',
    category: 'insurance',
    icon: 'shield-check',
    website: 'simplybusiness.com',
    authType: 'oauth2',
    tier: 5,
    docsUrl: 'https://simplybusiness.com/strategic-partnerships/',
    apiBaseUrl: 'https://api.simplybusiness.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Strategic partnership required',
  },
  {
    slug: 'buildops',
    name: 'BuildOps',
    description: 'Commercial contractor software',
    category: 'fsm',
    icon: 'wrench',
    website: 'buildops.com',
    authType: 'oauth2',
    tier: 5,
    docsUrl: 'https://developer.buildops.com',
    apiBaseUrl: 'https://api.buildops.com',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'electrical', 'construction'],
    rateLimits: 'Standard',
    notes: 'Contact required',
  },
  {
    slug: 'tyler-energov',
    name: 'Tyler EnerGov',
    description: 'Government permitting',
    category: 'government',
    icon: 'landmark',
    website: 'tylertech.com',
    authType: 'oauth2',
    tier: 5,
    docsUrl: 'https://tylertech.com',
    apiBaseUrl: 'https://api.tylertech.com',
    webhookSupport: false,
    trades: ['construction', 'general'],
    rateLimits: 'Standard',
    notes: 'Enterprise; docs upon request',
  },

  /* ---------------------------------------------------------------- */
  /*  TIER 6 — Special/Legacy (13)                                    */
  /* ---------------------------------------------------------------- */
  {
    slug: 'quickbooks-desktop',
    name: 'QuickBooks Desktop',
    description: 'Desktop accounting',
    category: 'accounting',
    icon: 'calculator',
    website: 'quickbooks.intuit.com',
    authType: 'api_key',
    tier: 6,
    docsUrl: 'https://developer.intuit.com',
    apiBaseUrl: 'http://localhost',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'N/A',
    notes: 'QBXML/SOAP via Web Connector; Use conductor.is for REST wrapper',
  },
  {
    slug: 'planswift',
    name: 'PlanSwift',
    description: 'Takeoff and estimating',
    category: 'estimating',
    icon: 'file-text',
    website: 'planswift.com',
    authType: 'api_key',
    tier: 6,
    docsUrl: 'https://planswift.com',
    apiBaseUrl: 'http://localhost',
    webhookSupport: false,
    trades: ['construction', 'general'],
    rateLimits: 'N/A',
    notes: 'Desktop SDK (COM/OLE); Email for access',
  },
  {
    slug: 'compliancequest',
    name: 'ComplianceQuest',
    description: 'Quality and compliance',
    category: 'compliance',
    icon: 'shield',
    website: 'compliancequest.com',
    authType: 'oauth2',
    tier: 6,
    docsUrl: 'https://compliancequest.com',
    apiBaseUrl: 'https://<instance>.salesforce.com',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Per Salesforce limits',
    notes: 'Salesforce Connected App; Requires Salesforce subscription',
  },
  {
    slug: 'sap-fsm',
    name: 'SAP Field Service Management',
    description: 'Enterprise FSM',
    category: 'fsm',
    icon: 'cloud',
    website: 'sap.com',
    authType: 'oauth2',
    tier: 6,
    docsUrl: 'https://github.com/SAP/fsm-sdk',
    apiBaseUrl: 'https://eu.coresuite.com/api',
    webhookSupport: true,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Official SDK available',
  },
  {
    slug: 'rsmeans',
    name: 'RSMeans (Gordian)',
    description: 'Construction cost data',
    category: 'estimating',
    icon: 'file-text',
    website: 'gordian.com',
    authType: 'api_key',
    tier: 6,
    docsUrl: 'https://dataapi-sb.gordian.com',
    apiBaseUrl: 'https://dataapi.gordian.com',
    webhookSupport: false,
    trades: ['construction', 'general'],
    rateLimits: 'Standard',
    notes: 'Annual subscription; Swagger docs',
  },
  {
    slug: 'clear-estimates',
    name: 'Clear Estimates (CEPIA)',
    description: 'Estimating software',
    category: 'estimating',
    icon: 'file-text',
    website: 'clearestimates.com',
    authType: 'api_key',
    tier: 6,
    docsUrl: 'https://clearestimates.com',
    apiBaseUrl: 'https://estimates.clearestimates.com',
    webhookSupport: false,
    trades: ['remodeling', 'general'],
    rateLimits: 'Standard',
    notes: 'Enterprise pricing',
  },
  {
    slug: 'gorilladesk',
    name: 'GorillaDesk',
    description: 'Pest control & lawn care',
    category: 'fsm',
    icon: 'wrench',
    website: 'gorilladesk.com',
    authType: 'bearer_token',
    tier: 6,
    docsUrl: 'https://api.gorilladesk.com',
    apiBaseUrl: 'https://api.gorilladesk.com',
    webhookSupport: false,
    trades: ['pest_control', 'lawn_care'],
    rateLimits: 'Standard',
    notes: 'REST V1+V2; email/password → token',
  },
  {
    slug: 'zipbooks',
    name: 'ZipBooks',
    description: 'Accounting software',
    category: 'accounting',
    icon: 'calculator',
    website: 'zipbooks.com',
    authType: 'jwt',
    tier: 6,
    docsUrl: 'https://developer.zipbooks.com',
    apiBaseUrl: 'https://api.zipbooks.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Unstable API; breaking changes expected',
  },
  {
    slug: 'sos-inventory',
    name: 'SOS Inventory',
    description: 'Inventory management for QBO',
    category: 'inventory',
    icon: 'package',
    website: 'sosinventory.com',
    authType: 'api_key',
    tier: 6,
    docsUrl: 'https://help.sosinventory.com',
    apiBaseUrl: 'https://api.sosinventory.com',
    webhookSupport: false,
    trades: ['all'],
    rateLimits: 'Standard',
    notes: 'Pull-only; Dev portal registration',
  },
  {
    slug: 'liberty-mutual-surety',
    name: 'Liberty Mutual Surety',
    description: 'Surety bonds',
    category: 'surety',
    icon: 'shield',
    website: 'libertymutual.com',
    authType: 'api_key',
    tier: 6,
    docsUrl: 'https://test-developers.libertymutual.com',
    apiBaseUrl: 'https://api.libertymutual.com',
    webhookSupport: false,
    trades: ['construction', 'general'],
    rateLimits: 'Standard',
    notes: 'Swagger docs',
  },
  {
    slug: 'merchants-bonding',
    name: 'Merchants Bonding',
    description: 'Surety bonds',
    category: 'surety',
    icon: 'shield',
    website: 'merchantsbonding.com',
    authType: 'api_key',
    tier: 6,
    docsUrl: 'https://merchantsbonding.com/tech-tools/api',
    apiBaseUrl: 'https://api.merchantsbonding.com',
    webhookSupport: false,
    trades: ['construction', 'general'],
    rateLimits: 'Standard',
  },
  {
    slug: 'interplay-learning',
    name: 'Interplay Learning',
    description: 'Trade skills training',
    category: 'training',
    icon: 'graduation-cap',
    website: 'interplaylearning.com',
    authType: 'api_key',
    tier: 6,
    docsUrl: 'https://interplaylearning.com',
    apiBaseUrl: 'https://api.interplaylearning.com',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'electrical'],
    rateLimits: 'Standard',
    notes: 'Reporting API; Enterprise plan only',
  },
  {
    slug: 'loc8',
    name: 'Loc8',
    description: 'Field service management',
    category: 'fsm',
    icon: 'wrench',
    website: 'loc8.com',
    authType: 'api_key',
    tier: 6,
    docsUrl: 'https://loc8.com',
    apiBaseUrl: 'https://api.loc8.com',
    webhookSupport: false,
    trades: ['hvac', 'plumbing', 'electrical', 'general'],
    rateLimits: 'Standard',
    notes: 'API-driven but no public docs; Contact directly',
  },
] as const;

/* ================================================================== */
/*  CATEGORY_LABELS                                                   */
/* ================================================================== */

export const CATEGORY_LABELS: Record<IntegrationCategory, string> = {
  payments: 'Payments',
  communication: 'Communication',
  scheduling: 'Scheduling',
  fleet: 'Fleet & GPS',
  accounting: 'Accounting',
  government: 'Government & Compliance',
  fsm: 'Field Service Management',
  crm: 'CRM',
  estimating: 'Estimating & Takeoff',
  measurement: 'Property Measurement',
  project_management: 'Project Management',
  inventory: 'Inventory & Supply',
  insurance: 'Insurance',
  surety: 'Surety & Bonds',
  training: 'Training',
  reputation: 'Reputation Management',
  proposals: 'Proposals',
  compliance: 'Compliance',
  specialty: 'Specialty Tools',
};

/* ================================================================== */
/*  TIER_LABELS                                                       */
/* ================================================================== */

export const TIER_LABELS: Record<IntegrationTier, { name: string; description: string }> = {
  1: { name: 'Instant Access', description: 'Free, instant API access' },
  2: { name: 'Dev Account', description: 'Free developer account + OAuth setup' },
  3: { name: 'Application Required', description: 'Developer application required' },
  4: { name: 'Paid Plan', description: 'Paid plan or subscription required' },
  5: { name: 'Partner Program', description: 'Partner or enterprise agreement' },
  6: { name: 'Special Access', description: 'Legacy, desktop SDK, or restricted' },
};

/* ================================================================== */
/*  Lookup Helpers                                                    */
/* ================================================================== */

/** Find a single integration by its URL-safe slug. */
export function getIntegrationBySlug(slug: string): IntegrationEntry | undefined {
  return INTEGRATIONS.find((i) => i.slug === slug);
}

/** Return all integrations that belong to a given category. */
export function getIntegrationsByCategory(category: IntegrationCategory): IntegrationEntry[] {
  return INTEGRATIONS.filter((i) => i.category === category);
}

/** Return all integrations that belong to a given access tier. */
export function getIntegrationsByTier(tier: IntegrationTier): IntegrationEntry[] {
  return INTEGRATIONS.filter((i) => i.tier === tier);
}
